---

- hosts: all
  become: true
  pre_tasks:

# Update Package Repositories
  - name: "Update Package Repositories"
    package:
      update_cache: yes  

# Install Packages
## Install BASE Applications
  - name: "Install the base applications"
    tags: always,base
    package: 
      name:
        - chrony
        - vim
      state: latest

## Install Web Server Packages
- hosts: [web_servers]
  become: true
  tasks:
  - name: "Install Web Server Packages to [web_servers]"
    tags: nginx
    package:
      name:
        - "{{ nginx_package }}"
      state: latest

## Install MariaDB Server Packages
- hosts: [msq_servers]
  become: true
  tasks:
  - name: "Install MariaDB Server Packages to [msq_servers]"
    tags: mariadb,db
    package:
      name:
        - "{{ msq_package }}"
      state: latest

## Install PostgreSQL Server Packages
- hosts: [psq_servers]
  become: true
  tasks:
  - name: "Install PostgreSQL Server Packages to [psq_servers]"
    tags: pgsql,db
    package:
      name:
        - "{{ pgsql_package }}"
      state: latest      