# MariaDB Server Role
## Install MariaDB Server Packages
- name: "Install MariaDB Server Packages to [msq_servers]"
  tags: mariadb,db
  package:
    name:
      - "{{ mariadb_package }}"
    state: latest

## Check MariaDB Service is Enabled and Running
- name: "Check mariadb is running"
  tags: mariadb
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes     

## Configure UFW for MariaDB
- name: Allow MariaDB in UFW
  ufw: rule=allow port="{{ mariadb_port }}" proto=tcp
  when: ansible_distribution == 'Ubuntu'