
filetype off
set ruler
set number
syntax on
filetype indent on
filetype plugin indent on
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
set tabstop=4
set shiftwidth=4
set textwidth=79
set expandtab
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set cursorline