# Base Role

## Install Packages
### Install BASE Applications
- name: "Install the BASE applications"
  tags: always,base
  package: 
    name:
      - chrony
      - vim
      - unzip
      - tree
      - neofetch
    state: latest

## Add ansible user      
- name: "Add 'ansible' user"
  tags: always,base
  user:
    name: ansible
    groups: root

- name: "Add Ansible SSH key"
  tags: always
  authorized_key:       
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHrF06u8laeF0spuUwdwVf7SLw/xah8vJkIZJ19RcySd ansible"

- name: "Add sudoers file for ansible user"
  tags: always
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root

## Setup dotfiles
## Deploy vimrc for david
- name: "Deploy user's .vimrc"
  tags: base,always
  copy: 
    src: vimrc
    dest: /home/david/.vimrc
    owner: david
    group: david
    mode: 0644          

## Deploy bashrc for david
- name: "Deploy user's .bashrc"
  tags: base,always
  copy: 
    src: bashrc
    dest: /home/david/.bashrc
    owner: david
    group: david
    mode: 0644    