# PostgreSQL Server Block
## Install PostgreSQL Server Packages
- name: "Install PostgreSQL Server Packages to [psq_servers]"
  tags: postgresql,db
  package:
    name:
      - "{{ postgresql_package }}"
    state: latest     

## Check PostgreSQL Service is Enabled and Running
- name: "Check postgresql is running"
  tags: postgresql
  service:
    name: "{{ postgresql_service }}"
    state: started
    enabled: yes 

## Configure UFW for PostgreSQL
- name: Allow PostgreSQL in UFW
  ufw: rule=allow port="{{ postgresql_port }}" proto=tcp
  when: ansible_distribution == 'Ubuntu'