## Install Packages

### Add required repositories
- name: Add Microsoft's VS Code Repository
  ansible.builtin.yum_repository:
    name: microsoft-vs-code
    description: "Microsoft VS Code"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    baseurl: "https://packages.microsoft.com/yumrepos/vscode"
  when: ansible_distribution == "Fedora"
  notify: dnf-check-update

- name: Add Vivaldi's Repository
  ansible.builtin.yum_repository:
    name: vivaldi
    description: "Vivaldi"
    baseurl: "https://repo.vivaldi.com/archive/rpm/$basearch"
    gpgkey: "https://repo.vivaldi.com/archive/linux_signing_key.pub"
  when: ansible_distribution == "Fedora"
  notify: dnf-check-update


- name: Install RPM Fusion (nonfree)
  yum:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm
    disable_gpg_check: true
    state: present
  notify: dnf-check-update
## Required for:
# - lpf-spotify-client


- name: Install RPM Fusion (free)
  yum:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm
    disable_gpg_check: true
    state: present
  notify: dnf-check-update
## Required for:
# - vlc


### Install WORKSTATION Applications
- name: "Install the WORKSTATION applications (Fedora)"
  tags: always,workstations
  package: 
    name:
      - screen
      - libreoffice.x86_64
      - libreoffice-langpack-en.x86_64
      - libreoffice-help-en.x86_64
      - libreoffice-base.x86_64
      - firefox
      - gnome-tweaks
      - code
      - gimp
      - gimp-help-en_GB.noarch
      - gnome-browser-connector
      - remmina
      - remmina-gnome-session
      - remmina-plugins-rdp
      - '@virtualization'
      - lpf-spotify-client
      - vivaldi-stable
      - vlc
      - timeshift
    state: latest
  when: ansible_distribution == "Fedora"