## Install Packages

### Add required repositories
- name: Add Microsoft's VS Code Repository
  ansible.builtin.yum_repository:
    name: microsoft-vs-code
    description: "Microsoft VS Code"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    baseurl: "https://packages.microsoft.com/yumrepos/vscode"
  when: ansible_distribution == "Fedora"
  notify: dnf-check-update

- name: Add Vivaldi's Repository
  ansible.builtin.yum_repository:
    name: vivaldi
    description: "Vivaldi"
    baseurl: "https://repo.vivaldi.com/archive/rpm/$basearch"
    gpgkey: "https://repo.vivaldi.com/archive/linux_signing_key.pub"
  when: ansible_distribution == "Fedora"
  notify: dnf-check-update


- name: Install RPM Fusion (nonfree)
  yum:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm
    disable_gpg_check: true
    state: present
  notify: dnf-check-update
## Required for:
# - lpf-spotify-client


- name: Install RPM Fusion (free)
  yum:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm
    disable_gpg_check: true
    state: present
  notify: dnf-check-update
## Required for:
# - vlc


### Install WORKSTATION Applications
- name: "Install the WORKSTATION applications (Fedora)"
  tags: always,workstations
  package: 
    name:
      - screen
      - libreoffice.x86_64
      - libreoffice-langpack-en.x86_64
      - libreoffice-help-en.x86_64
      - libreoffice-base.x86_64
      - firefox
      - gnome-tweaks
      - code
      - gimp
      - gimp-help-en_GB.noarch
      - gnome-browser-connector
      - gnome-tweaks
      - gnome-terminal      
      - lpf-spotify-client
      - vivaldi-stable
      - vlc
      - timeshift
      - wireguard-tools  
      - conky   
    state: latest
  when: ansible_distribution == "Fedora"

  
### Configure GUI (Gnome)
#### Install Pre-requisites
- name: "Deploy gnome-terminal configuration"
  tags: workstations,gnome
  package:
    name:
      - dconf
      - gnome-terminal
      - python3-psutil
    state: latest
- name: "Copy gnome config file to /tmp"
  tags: workstations,gnome
  copy:
    src: gnome_dconf_dump
    dest: /tmp/gnome_dconf_dump
    owner: "{{primary_user}}"
    group: "{{primary_user}}"
    mode: 0600    
- name: "Deploy gnome dconf file"
  tags: workstations,gnome
  ansible.builtin.command:
    cmd: dconf load -f /org/gnome/ < ./gnome_dconf_dump
    chdir: /tmp

#### Configure Conky
- name: "Deploy conky.config"
  tags: workstations
  copy: 
    src: conky.conf
    dest: /home/{{primary_user}}/.config/conky/conky.conf
    owner: "{{primary_user}}"
    group: "{{primary_user}}"
    mode: 0600
- name: "Deploy conky.desktop"
  tags: workstations
  copy: 
    src: conky_autostart.desktop
    dest: /home/{{primary_user}}/.config/autostart/conky_autostart.desktop
    owner: "{{primary_user}}"
    group: "{{primary_user}}"
    mode: 0600    